#!/usr/bin/env python3
# -*- mode: python -*-

import subprocess
import textwrap

if __name__ == '__main__':
    args = ['emacs', '-q', '--batch', '-L', '.', '-l', 'libtripoli']
    code = textwrap.dedent("""
    import code
    c = code.InteractiveConsole()
    c.push('import tripoli')
    c.push('import emacs_raw as er')
    c.push('import emacs as e')
    c.interact()
    """)
    args.extend(['--eval', '(tripoli-run-string "{}")'.format(code)])
    subprocess.run(args, check=True)
